---
openshift_cluster_content:
- object: app-builds
  content:
  - name: app-build
    template: "{{ inventory_dir }}/../templates/binary-template-with-secrets.yml"
    params_from_vars: "{{ build }}"
    tags:
    - build
- object: dev-stage
  content:
  - name: postgresql-dev-deploy
    template: "{{ inventory_dir }}/../templates/postgresql-persistent.yml"
    params_from_vars: "{{ database }}"
    namespace: "{{ dev_namespace }}"
    tags:
    - deploy
    - dev-deploy
  - name: app-dev-deploy
    template: "{{ inventory_dir }}/../templates/django-psql-persistent.yml"
    params_from_vars: "{{ dev }}"
    namespace: "{{ dev_namespace }}"
    tags:
    - deploy
    - dev-deploy
- object: test-stage
  content:
  - name: postgresql-test-deploy
    template: "{{ inventory_dir }}/../templates/postgresql-persistent.yml"
    params_from_vars: "{{ database }}"
    namespace: "{{ test_namespace }}"
    tags:
    - deploy
    - test-deploy
  - name: app-test-deploy
    template: "{{ inventory_dir }}/../templates/django-psql-persistent.yml"
    params_from_vars: "{{ test }}"
    namespace: "{{ test_namespace }}"
    tags:
    - deploy
    - test-deploy
