---
openshift_cluster_content:
- object: app-builds
  content:
  - name: app-build
    template: "{{ inventory_dir }}/../templates/binary-template-with-secrets.yml"
    params_from_vars: "{{ build }}"
    tags:
    - build
- object: dev-stage
  content:
  - name: app-dev-deploy
    template: "{{ inventory_dir }}/../templates/django-psql-persistent.yml"
    params_from_vars: "{{ dev }}"
    namespace: "{{ dev_namespace }}"
    tags:
    - deploy
    - dev-deploy
# - object: test-stage
#   content:
#   - name: app-test-deploy
#     template: "{{ inventory_dir }}/../templates/deployment.yml"
#     params_from_vars: "{{ deploy }}"
#     namespace: "{{ test_namespace }}"
#     tags:
#     - deploy
#     - test-deploy